package bangumi

import (
	"encoding/json"
	"github.com/jmoiron/sqlx"
	"strings"
)

type bgmCache struct {
	Title string
	Data  AutoGenerated2
	TTL   int64
}

var Bgmcache = bgmCache{}

func QueryBGM(Db *sqlx.DB) string {
	var data []byte
	_ = Db.QueryRow(`SELECT value
		FROM typecho_options
		WHERE name='plugin:GoBangumiList' `).Scan(&data)
	m := struct {
		UserID string
		AppID  string
	}{}
	json.Unmarshal(data, &m)
	var b strings.Builder
	b.WriteString("https://api.bgm.tv/user/")
	b.WriteString(m.UserID)
	b.WriteString("/collections/anime?app_id=")
	b.WriteString(m.AppID)
	b.WriteString("&max_results=99")
	return b.String()
}
