# .github/workflows/release.yaml

on:
  push: # 每次 push 的时候触发
  workflow_dispatch:

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

#      - name: Install dependencies
#        run: |
#          go version
#          go get -u github.com/BapiGso/SMOE

      - name: Build
        run: |
          go build -o SMOE_linux_amd64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o SMOE_windows_amd64.exe
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o SMOE_mac_amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o SMOE_linux_arm
          CGO_ENABLED=0 GOOS=windows GOARCH=arm go build -o SMOE_windows_arm.exe
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o SMOE_mac_arm

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          files: |
            SMOE_windows_amd64.exe
            SMOE_linux_amd64
            SMOE_mac_amd64
            SMOE_windows_arm.exe
            SMOE_linux_arm
            SMOE_mac_arm
