# .github/workflows/release.yaml

on:
  push: # 每次 push 的时候触发
  workflow_dispatch:

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # checkout 代码
      - uses: actions/setup-go@v2 # 配置 Go 环境
        with:
          go-version: "1.19.3" # 改成自己的版本

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/laszlocph/woodpecker

      - name: Debug
        run: |
          pwd
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
          echo ${GOPATH}
          echo ${GOROOT}
        env:
          GOPATH: /home/runner/work/woodpecker/go

      - name: Build
        run: |
        go build -o SMOE_linux_amd64 # 这 3 条是交叉编译 Go 的指令，酌情修改。
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o SMOE_windows_amd64.exe
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o SMOE_mac_amd64
        CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o SMOE_linux_arm
        CGO_ENABLED=0 GOOS=windows GOARCH=arm go build -o SMOE_windows_arm.exe
        CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o SMOE_mac_arm
        env:
          - GOPATH: /home/runner/work/woodpecker/go

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          files: |
            SMOE_windows_amd64.exe
            SMOE_linux_amd64
            SMOE_mac_amd64
            SMOE_windows_arm.exe
            SMOE_linux_arm
            SMOE_mac_arm
